- module: postgresql
  enabled: false
#  metricsets: ["database","bgwriter","activity"]
  # The host must be passed as PostgreSQL URL. Example:
  # postgres://localhost:5432?sslmode=disable
  # The available parameters are documented here:
  # https://godoc.org/github.com/lib/pq#hdr-Connection_String_Parameters
#  hosts: [ "postgres://postgres:5432?sslmode=disable" ]
  hosts: [ "postgres://postgres:5432?sslmode=disable" ]
  username: username
  password: password
  period: 10s
