---
apiVersion: v1
kind: Service
metadata:
  name: mod1-agm-postgresql
  labels:
    app.kubernetes.io/name: mod1-agm-postgresql
spec:
  selector:
    app.kubernetes.io/name: mod1-agm-postgresql
  type: ClusterIP
  ports:
      - port: 5432
