---
apiVersion: v1
kind: Service
metadata:
  name: mod1-gcm-mongodb
  labels:
    app.kubernetes.io/name: mod1-gcm-mongodb
spec:
  selector:
    app.kubernetes.io/name: mod1-gcm-mongodb
  clusterIP: None
  ports:
    - port: 27017
      protocol: TCP
