heartbeat.monitors:

  #Monitor all containers using an icmp ping
  - type: icmp
    schedule: '*/5 * * * * * *'
    hosts: ["metricbeat","elasticsearch","kibana","kafka","apm-server"]
    ipv4: true
    ipv6: true
    mode: any
    timeout: 3s
    wait: 1s

  #Monitor the Elasticsearch instance.
  - type: http
    enabled: true
    schedule: '@every 5s'
    urls: ["http://elasticsearch:9200"]
    ipv4: true
    ipv6: true
    mode: any
    timeout: 3s
#    username: '${ES_USERNAME:elastic}'
#    password: '${ES_PASSWORD:changeme}'
    check.request:
      method: "GET"
    check.response:
      status: 200

  #Monitor the Kibana instance.
  - type: http
    enabled: true
    schedule: '@every 5s'
    urls: ["http://kibana:5601/api/status"]
    ipv4: true
    ipv6: true
    mode: any
    timeout: 3s
    check.request:
      method: "GET"
    check.response:
      status: 200

  #Monitor the micro-services
  - type: http
    enabled: true
    schedule: '@every 5s'
    urls: [
        "http://dsa-service:9090/manage/health",
        "http://pcm-service:9090/manage/health",
        "http://agm-service:9090/manage/health",
        "http://gcm-service:9090/manage/health"
    ]
    mode: any
    timeout: 3s
    check.request:
      method: "GET"
    check.response:
      status: 200


processors:
  - add_docker_metadata: ~

monitoring.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

logging.to_files: false
