---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ecms-dsa-stripprefix
  labels:
    app.kubernetes.io/name: contingency-guard-system
spec:
  stripPrefix:
    prefixes:
      - /dsa
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mod1-dsa-service
  labels:
    app.kubernetes.io/name: contingency-guard-system
spec:
  entryPoints:
    - http
  routes:
    - kind: Rule
      match: Host(`ecms.apps.yggdrasill.tld`) && PathPrefix(`/dsa`)
      middlewares:
        - name: ecms-dsa-stripprefix
      services:
        - name: mod1-dsa-service
          port: 8091
