apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mod1-gcm-service
  labels:
    app.kubernetes.io/name: mod1-gcm-service
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - endpoints
  - namespaces
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mod1-gcm-service
  labels:
    app.kubernetes.io/name: mod1-gcm-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mod1-gcm-service
subjects:
- kind: ServiceAccount
  name: default
